#!/bin/bash

set -euox pipefail

# Load environment variables from .env file
if [ -f .env ]; then
    export $(cat .env | sed 's/#.*//g' | xargs)
fi

# Make sure we are not running this from the `scripts` directory
if [ -f migrate ]; then
    echo "Please run this script from the root directory of the project"
    exit 1
fi

# Make sure the first argument to the script is `up` or `down`
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <up|down>"
    exit 1
fi

# Generate PostgreSQL URL using the .env file
POSTGRES_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# Run migrations using golang-migrate
migrate -database "${POSTGRES_URL}?sslmode=disable" -path db/migrations $1
