version: "3.8"
services:
  # server:
  #   build:
  #     context: ./colaco-server
  #     dockerfile: ./colaco-server/docker/server.Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./colaco-server/.env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "${DB_USER}_${APP_ENV}"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
