version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      somenet:
        ipv4_address: 172.20.0.2
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "${DB_USER}_${APP_ENV}"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      somenet:
        ipv4_address: 172.20.0.3
volumes:
  postgres_data:

networks:
  somenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
